In [1]:
# load data
import pandas as pd
import numpy as np

def user_music_rate(filename):
    df = pd.read_csv(filename, engine = 'python')
    
    # drop music_id is 0
    df = df[df['music_id'] != 0]
    
    df['music_id'] = df["music_id"].astype('str')
    df['user_id'] = df["user_id"].astype('str')

    rate = df.play_len/df.music_len
    # replace invalid value
    rate = rate.replace([np.inf, -np.inf], -1)
    df['rate'] = rate
    # generate feature abnormal_rate; a song is repeated more than 30 times, drop abnormal
    df = df[(df['rate']>= 0) & (df['rate'] <= 30)]
    
    # generate rating
    df['rating'] = np.nan
    df.loc[df['rate']<=0.2,'rating'] = 1
    df.loc[(df['rate']>0.2) & (df['rate']<=0.5) ,'rating'] = 2
    df.loc[(df['rate']>0.5) & (df['rate']<=0.7) ,'rating'] = 3
    df.loc[(df['rate']>0.7) & (df['rate']<=0.8) ,'rating'] = 4
    df.loc[(df['rate']>0.8), 'rating'] = 5
    
    # return df[['user_id', 'music_id', 'rate']]
    return df[['user_id', 'music_id', 'rating']]

In [8]:
file = ['0301_c1.csv', '0302_c1.csv', '0303_c1.csv']
df_for_recommender = [user_music_rate(name) for name in file]

In [11]:
total = df_for_recommender[0].append([df_for_recommender[1], df_for_recommender[2]])
total.to_csv('0301_3_rating.csv', index=False)

In [12]:
tot = pd.read_csv('0301_3_rating.csv', engine = 'python')

In [13]:
tot

           user_id  music_id  rating
0        154421907   6560858     3.0
1        154410267   6777172     3.0
2        154407793  19472465     1.0
3        154422681    891952     5.0
4        154408091   4623962     5.0
5        154422571    703750     5.0
6        154417311   6491500     2.0
7        154421166   1967689     3.0
8        154421859   6126586     1.0
9        154422660  11914644     5.0
10       154422590   6468891     5.0
11       154419565  15196649     1.0
12       154422443   6247282     1.0
13       154412729   4357368     1.0
14       153985859   6762438     5.0
15       154408044   9374861     5.0
16       154413530    848918     1.0
17       154408915   7200911     5.0
18       154414399   3224320     5.0
19       154417195     78975     1.0
20       154422564  20804585     5.0
21       154415001   9812248     5.0
22       154422676  20271459     5.0
23       154421336   5011381     5.0
24       154422461   2280245     1.0
25       154412161   6651913     5.0
26       154422832   1217815     4.0
27       154412658   1161336     5.0
28       154412729   1076088     1.0
29       154422328   1004773     1.0
...            ...       ...     ...
6035289  154523085  20861482     5.0
6035290  154801848    666052     5.0
6035291  154803198   4430535     1.0
6035292  154503081    221380     2.0
6035293  154737280   1650214     5.0
6035294  154833778   5114569     1.0
6035295  154613503   6245379     3.0
6035296   37025504   3524422     2.0
6035297  154530853    708313     5.0
6035298  154608497   4395129     1.0
6035299    1883192   4705913     2.0
6035300    1749320   1691029     5.0
6035301  154771413  15249349     1.0
6035302  154729816    295586     1.0
6035303  154830111  16641137     1.0
6035304  154709758   7183465     1.0
6035305  154476681    335014     3.0
6035306  154771413  15249349     1.0
6035307  154826954   4779305     1.0
6035308  154484167  16543605     5.0
6035309   37025504   4365956     5.0
6035310  154517011    547912     5.0
6035311  155150037   1246590     5.0
6035312  154678526  20275342     3.0
6035313  154447284    402574     5.0
6035314  154604203   9952428     5.0
6035315   28638487   5017334     2.0
6035316  154575344  20673468     3.0
6035317  154603566   7119332     4.0
6035318  154831299    294397     1.0

[6035319 rows x 3 columns]